import XCTest

// UAE7Guard Screenshot Tests for App Store
// This file should be added to your Xcode project's UI Test target

class UAE7GuardSnapshotTests: XCTestCase {

    override func setUp() {
        super.setUp()

        let app = XCUIApplication()
        setupSnapshot(app)
        app.launch()

        continueAfterFailure = false
    }

    override func tearDown() {
        super.tearDown()
    }

    func testTakeAppStoreScreenshots() {
        let app = XCUIApplication()

        // Wait for app to fully load
        sleep(3)

        // 1. Home/Landing Screen
        snapshot("01-Home-Screen")
        sleep(2)

        // 2. Navigate to Verification Screen
        // Tap on verify button or navigate to verification page
        if app.buttons["Verify"].exists {
            app.buttons["Verify"].tap()
            sleep(2)
            snapshot("02-Verification-Report")
        }

        // 3. Navigate to Dashboard/Analytics
        if app.buttons["Dashboard"].exists {
            app.buttons["Dashboard"].tap()
            sleep(2)
            snapshot("03-Platform-Analytics")
        }

        // 4. Navigate to Wallet Examples
        if app.buttons["Learn"].exists {
            app.buttons["Learn"].tap()
            sleep(2)
            snapshot("04-Known-Wallet-Examples")
        }

        // 5. Navigate to AI Prediction/Analysis
        // This depends on your navigation structure
        // Adjust based on actual button/tab names
        if app.buttons["AI Predict"].exists {
            app.buttons["AI Predict"].tap()
            sleep(2)
            snapshot("05-AI-Analysis")
        }
    }

    func testAdditionalScreenshots() {
        let app = XCUIApplication()

        // Additional screenshots if needed

        // 6. Settings or Account screen
        if app.buttons["Account"].exists {
            app.buttons["Account"].tap()
            sleep(2)
            snapshot("06-Account-Settings")
        }

        // 7. Terms & Conditions screen
        if app.staticTexts["Terms & Conditions"].exists {
            app.staticTexts["Terms & Conditions"].tap()
            sleep(2)
            snapshot("07-Terms-Conditions")
        }
    }
}

// MARK: - Helper Extensions

extension XCUIApplication {
    func tapCoordinate(at point: CGPoint) {
        let normalized = coordinate(withNormalizedOffset: .zero)
        let offset = CGVector(dx: point.x, dy: point.y)
        let coordinate = normalized.withOffset(offset)
        coordinate.tap()
    }
}

// MARK: - Setup Instructions
/*

 TO USE THIS FILE:

 1. Open your Xcode project: ios/App/App.xcworkspace

 2. Create a new UI Test target if you don't have one:
    - File → New → Target → iOS UI Testing Bundle
    - Name it "AppUITests"

 3. Add this file to the UI Test target:
    - Drag this file into the AppUITests folder in Xcode

 4. Install Fastlane Snapshot:
    - sudo gem install fastlane
    - cd ios/App
    - fastlane snapshot init

 5. Add SnapshotHelper to your project:
    - It will be generated by `fastlane snapshot init`
    - Add it to your UI Test target

 6. Update button/element names in the test:
    - Use the actual accessibility identifiers or text from your app
    - You can find these using Xcode's Accessibility Inspector

 7. Run the tests:
    - cd ios/App
    - fastlane snapshot

 8. Screenshots will be saved in:
    - ios/App/screenshots/

 TIPS:
 - Add accessibility identifiers to your buttons for easier testing
 - Use sleep() to wait for animations/data loading
 - Test on one device first before running on all devices
 - Check the screenshots folder after the first run

 */
